### ISSUE TITLE
Private/public repo status

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron_nodes#37]
#3 and #36 both stem from the fact this is a private repo. What are our conditions for taking the repo public?

**Comment by jan-janssen** [comment]
Done

**Comment by liamhuber** [comment]
I think as long as we avoid making conda releases of it (I.e. no release tags, and I can even disable the release CI), the in-development status should stay sufficiently clear as we'll only have users who are explicitly cloning the repo 👍
